sequenceDiagram
    participant Product as Product<br>[implements GapPeripheralResponse]
    participant CN as CN<br>[implements GapPeripheral]
    Product->>CN: GapPeripheral.RemoveOldestBond()
    CN-->>Product: GapPeripheralResponse.NumberOfBondsChanged(0)
