---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      minor-and-patch-action-updates:
        update-types:
          - minor
          - patch
  - package-ecosystem: docker
    directory: .clusterfuzzlite
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: .devcontainer
    schedule:
      interval: daily
