ENABLE:
  - ACTION
  - CPP
  - DOCKERFILE
  - JSON
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - XML
  - YAML
DISABLE_LINTERS:
  - CPP_CPPLINT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_SEMGREP
  - SPELL_CSPELL
  - JSON_V8R
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - SPELL_PROSELINT
  - SPELL_LYCHEE
CPP_CLANG_FORMAT_FILTER_REGEX_EXCLUDE: (external)
SPELL_PROSELINT_FILE_EXTENSIONS: [".md", ".adoc"]
SARIF_REPORTER: true
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: false
REPOSITORY_GOODCHECK_RULES_PATH: .github/linters
JSON_JSONLINT_ARGUMENTS: --mode cjson
