ENABLE:
  - DOCKERFILE
  - JSON
  - MARKDOWN
  - SPELL
  - YAML
DISABLE_LINTERS:
  - JSON_JSONLINT
  - SPELL_CSPELL
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
PRINT_ALPACA: false
FLAVOR_SUGGESTIONS: false
SHOW_SKIPPED_LINTERS: false
ADDITIONAL_EXCLUDED_DIRECTORIES: [external, lwip-2.1.1]
