ENABLE:
  - ACTION
  - DOCKERFILE
  - JSON
  - MARKDOWN
  - SPELL
  - YAML
DISABLE_LINTERS:
  - JSON_JSONLINT
  - SPELL_CSPELL
  - JSON_V8R
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - SPELL_PROSELINT
SPELL_PROSELINT_FILE_EXTENSIONS: [".md", ".adoc"]
SARIF_REPORTER: true
PRINT_ALPACA: false
FLAVOR_SUGGESTIONS: false
SHOW_SKIPPED_LINTERS: false
ADDITIONAL_EXCLUDED_DIRECTORIES: [external, lwip-2.1.1]
