ENABLE:
  - ACTION
  - DOCKERFILE
  - JSON
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - XML
  - YAML
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_SEMGREP
  - SPELL_CSPELL
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
SPELL_PROSELINT_FILE_EXTENSIONS: [".md", ".adoc"]
SARIF_REPORTER: true
PRINT_ALPACA: false
FLAVOR_SUGGESTIONS: false
SHOW_SKIPPED_LINTERS: false
ADDITIONAL_EXCLUDED_DIRECTORIES: [external, lwip-2.1.1]
REPOSITORY_GOODCHECK_CONFIG_FILE: .github/linters/goodcheck.yml
