ENABLE:
  - ACTION
  - DOCKERFILE
  - JSON
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - XML
  - YAML
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_SEMGREP
  - SPELL_CSPELL
  - JSON_V8R
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - SPELL_PROSELINT
  - SPELL_LYCHEE
SPELL_PROSELINT_FILE_EXTENSIONS: [".md", ".adoc"]
SARIF_REPORTER: true
PRINT_ALPACA: false
FLAVOR_SUGGESTIONS: false
SHOW_SKIPPED_LINTERS: false
ADDITIONAL_EXCLUDED_DIRECTORIES: [external, lwip-2.1.1]
REPOSITORY_GOODCHECK_RULES_PATH: .github/linters
JSON_JSONLINT_ARGUMENTS: --mode cjson
REPOSITORY_GITLEAKS_ARGUMENTS: -r gitleaks_report.json
