sequenceDiagram
    title GATT Discovery Flow Example: Pulse Oximeter (PLX)

    participant Product as Product<br>[implements GattClientResponse]
    participant CN as CN<br>[implements GattClient]

    Product->>CN: StartServiceDiscovery()
    CN-->>Product: ServiceDiscovered(uuid=0x1801)
    CN-->>Product: ServiceDiscovered(uuid=0x1800)
    CN-->>Product: ServiceDiscovered(uuid=0x180A)
    CN-->>Product: ServiceDiscovered(<br>uuid=1bc5d5a502005e8be2115f0de070a946)
    CN-->>Product: ServiceDiscovered(<br>uuid=0x1822, handles={startHandle=64, endHandle=69})
    CN-->>Product: ServiceDiscovered(uuid=0x180F)
    CN-->>Product: ServiceDiscovered(uuid=0x180D)
    CN-->>Product: ServiceDiscoveryComplete()

    Product->>CN: StartCharacteristicDiscovery(<br>startHandle=64, endHandle=69)
    CN-->>Product: CharacteristicDiscovered(<br>uuid=0x2A5F, handle=65, valueHandle=66, properties=0x10)
    CN-->>Product: CharacteristicDiscovered(<br>uuid=0x2A60, handle=68, valueHandle=69, properties=0x02)
    CN-->>Product: CharacteristicDiscoveryComplete()

    Product->>CN: StartDescriptorDiscovery(<br>startHandle=66, endHandle=67)
    CN-->>Product: DescriptorDiscovered(uuid=0x2902, handle=67)
    CN-->>Product: DescriptorDiscoveryComplete()

    Product->>CN: WriteDescriptor(handle=67, data=0x0100)
    CN-->>Product: OperationComplete(success)

    CN-->>Product: NotificationReceived(<br>handle=66, data=<PLX Continuous Measurement bytes>)
