#define configMAX_SYSCALL_INTERRUPT_PRIORITY 0
#define configMINIMAL_STACK_SIZE 1
#define configMAX_PRIORITIES 1
#define configUSE_PREEMPTION 1
#define configUSE_IDLE_HOOK 0
#define configUSE_TICK_HOOK 0
#define configUSE_16_BIT_TICKS 0
#define configKERNEL_INTERRUPT_PRIORITY 0
#define configCPU_CLOCK_HZ 1
#define configTICK_RATE_HZ 1
#define configTOTAL_HEAP_SIZE 1
