---
###########################################
# These are the rules used for            #
# linting all the yaml files in the stack #
# NOTE:                                   #
# You can disable line with:              #
# # yamllint disable-line                 #
###########################################
extends: default
rules:
  new-lines:
    level: warning
    type: unix
  line-length:
    max: 500
