sequenceDiagram
    participant App as App<br>[implements GapCentralResponse]
    participant Node as Node<br>[implements GapCentral]
    App->>Node: GapCentral.GetState()
    Node-->>App: GapCentralResponse.CurrentState(standby)
