sequenceDiagram
    participant App as App<br>[implements GapCentralResponse]
    participant Node as Node<br>[implements GapCentral]
    Note over App, Node: Standby() is allowed from scanning,<br>connected or initiating. It terminates the current<br>activity and returns the Node to standby.
    App->>Node: GapCentral.Standby()
    Node-->>App: GapCentralResponse.CurrentState(standby)
