sequenceDiagram
    participant Product as Product<br>[implements GapCentralResponse]
    participant CN as CN Central<br>[implements GapCentral]
    Note over Product, CN: Standby() is allowed from scanning,<br>connected or initiating. It terminates the current<br>activity and returns the CN to standby.
    Product->>CN: GapCentral.Standby()
    CN-->>Product: GapCentralResponse.CurrentState(standby)
