#ifndef LWIP_LWIPOPTS_H
#define LWIP_LWIPOPTS_H

#include "stdint.h"

#ifdef __cplusplus
extern "C"
{
#endif

#define NO_SYS 1
#define LWIP_IPV6 1
#define SYS_LIGHTWEIGHT_PROT 0
#define LWIP_NETCONN 0
#define LWIP_SOCKET 0
#define LWIP_DHCP 1
#define LWIP_DHCP_CHECK_LINK_UP 1
#define LWIP_AUTOIP 1
#define LWIP_DHCP_AUTOIP_COOP 1
#define LWIP_DNS 1
#define LWIP_RAW 0
#define LWIP_IGMP 1
uint32_t StaticLwIpRand();
#define LWIP_RAND() StaticLwIpRand()
#define MEM_ALIGNMENT 4
#define LWIP_STATS 0

#define LWIP_DNS_SECURE 0

#define MEM_SIZE 3200

#ifndef LWIP_CHECKSUM_IN_SOFTWARE
#define LWIP_CHECKSUM_IN_SOFTWARE 0
#endif
#define CHECKSUM_GEN_IP LWIP_CHECKSUM_IN_SOFTWARE
#define CHECKSUM_GEN_UDP LWIP_CHECKSUM_IN_SOFTWARE
#define CHECKSUM_GEN_TCP LWIP_CHECKSUM_IN_SOFTWARE
#define CHECKSUM_GEN_ICMP LWIP_CHECKSUM_IN_SOFTWARE
#define CHECKSUM_CHECK_IP LWIP_CHECKSUM_IN_SOFTWARE
#define CHECKSUM_CHECK_UDP LWIP_CHECKSUM_IN_SOFTWARE
#define CHECKSUM_CHECK_TCP LWIP_CHECKSUM_IN_SOFTWARE

#define LWIP_NETIF_HOSTNAME 1
#define LWIP_NETIF_EXT_STATUS_CALLBACK 1
#define SO_REUSE 1

#define LWIP_TCP_PCB_NUM_EXT_ARGS 1

#define LWIP_DHCP_AUTOIP_COOP_TRIES 5

#ifdef __cplusplus
}
#endif

#endif
