classDiagram
    class BinaryPipePatternSend {
        <<service id=111>>
        +SendData()
    }
    class BinaryPipePatternSendResponse {
        <<service id=112>>
        +SendCompleted()
    }
    BinaryPipePatternSend --> BinaryPipePatternSendResponse : responses