---
name: Build & Publish Documentation

on:
  push:

env:
  SITE_DIR: "site"
jobs:
  build_antora:
    name: Build Antora Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Antora Site
        uses: kameshsampath/antora-site-action@6069ae47f8c6dfd2a7c842d2dea766c639ab0053
        with:
          antora_playbook: antora-playbook.yml
          antora_generator: "antora-site-generator-lunr"
          antora_docsearch_enabled: "true"
          antora_docsearch_index_version: "latest"
      - name: Store Antora Site
        uses: actions/upload-artifact@v1.0.0
        with:
          name: antora
          path: "${{ github.workspace }}/build/${{ env.SITE_DIR }}"
  deploy_antora:
    runs-on: ubuntu-latest
    needs: build_antora
    if: ${{ github.ref == 'refs/heads/develop' }}
    name: Publish to GitHub Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve Antora Site
        uses: actions/download-artifact@v1
        with:
          name: antora
          path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.SITE_DIR }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
